services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=edward_school_db'
      - 'POSTGRES_PASSWORD=edward.school'
      - 'POSTGRES_USER=edward'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
